plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT' apply(false)
    id 'net.neoforged.moddev.legacyforge' version '2.0.87' apply(false)
}

repositories {
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}