# Important Notes:
# fabric.mod.json's modid field cannot be expanded, you must change it manually.
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.4.3
group=com.jdolphin.ricksportalgun
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Rick's Portal Gun
mod_author=1JamesLeDolphin
mod_id=ricksportalgun
license=ARR
credits=SamTees, HeyHey37, TheMajorNoob_239, Gol D. Crow, Kiseki
description=Adds Rick's portal gun from the sci-fi show Rick and Morty
minecraft_version_range=[1.20.1, 1.20.2)
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.20.1
parchment_version=2023.09.03

config_version=8.0.2
jei_version=15.20.0.116
emi_version=1.1.22+1.20.1
immersive_portals_version=v3.3.9-mc1.20.1
# Fabric
fabric_version=0.92.2+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.4.0
forge_loader_version_range=[47,)

neoforge_version=47.4.0
neoforge_loader_version_range=[47,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
