# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.4.0
group=com.jdolphin.ricksportalgun
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Rick's Portal Gun
mod_author=1JamesLeDolphin
mod_id=ricksportalgun
license=ARR
credits=SamTees, HeyHey37, TheMajorNoob_239, Gol D. Crow, Kiseki
description=Adds Rick's portal gun from the sci-fi show Rick and Morty
minecraft_version_range=[1.21.1, 1.21.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Config lib version
config_version=21.1.3

# Fabric
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.14

# Forge
forge_version=52.1.0
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.192
neoforge_loader_version_range=[1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
