plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    validateAccessTransformers = true

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }

    maven { url 'https://jitpack.io' }

    // the repository for Cloth Config
    maven { url 'https://maven.shedaniel.me' }

    //CC Tweaked
    maven {
        url "https://maven.squiddev.cc"
        content {
            includeGroup("cc.tweaked")
        }
    }

    // Create, Ponder, Flywheel
    maven {
        url = "https://maven.createmod.net"
    }
    // Registrate
    maven {
        url = "https://maven.ithundxr.dev/mirror"
    }
    // ForgeConfigAPIPort
    maven {
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }

}

dependencies {
    compileOnly project(":common")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")

    //JEI
    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    modCompileOnlyApi("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    //modRuntimeOnly  "mezz.jei:jei-${minecraft_version}-forge:${jei_version}"

    //EMI
    modCompileOnlyApi "dev.emi:emi-forge:${emi_version}:api"
    modRuntimeOnly "dev.emi:emi-forge:${emi_version}"

    //Infinite Dimensions
    modCompileOnly("maven.modrinth:infinite-dimensions:2.4.11+1.20.1-forge")
    //modRuntimeOnly("maven.modrinth:infinite-dimensions:2.4.11+1.20.1-forge")

    modRuntimeOnly("maven.modrinth:architectury-api:9.2.14+forge")
    modRuntimeOnly("maven.modrinth:forgified-fabric-api:0.92.6+1.11.14+1.20.1")

    //Immersive portals
    modImplementation("curse.maven:immersive-portals-for-forge-355440:6368524")
    modRuntimeOnly("curse.maven:cloth-config-348521:5729105")

    //CC Tweaked
    modCompileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-core-api:${cct_version}")
    modCompileOnly("cc.tweaked:cc-tweaked-${minecraft_version}-forge-api:${cct_version}")
    //modRuntimeOnly("cc.tweaked:cc-tweaked-${minecraft_version}-forge:${cct_version}")

    //Create Stuff
    modImplementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")
    modCompileOnly("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}")
    modRuntimeOnly("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}")
    modImplementation("com.tterrag.registrate:Registrate:${registrate_version}")
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation("io.github.llamalad7:mixinextras-forge:0.4.1")

    modCompileOnly("maven.modrinth:embeddium:0.3.31+mc1.20.1")
    modCompileOnly("maven.modrinth:oculus:1.20.1-1.8.0")
}

jar {
    finalizedBy('reobfJar')
}
